apiVersion: v1
kind: Pod
metadata:
  name: [[forms[0].name]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
spec:
replicas: 1
  containers:
    - image: [[forms[0].image]]
      name: [[forms[0].name]]
      ports:
      resources: {}
      - containerPort: 80
        protocol: TCP 